/*
CREA UNA FUNCION QUE RECIBIA UN ARRAY CON CADENA DE CARACTERES Y QUE DEVUELVA LAS QUE TENGAN UNA LONGITUD MAYOR A 3
CREAR OTRA FUNCION QUE RECIBIA NUMEROS Y QUE DEVUELVE LOS PARES
CREAR OTRA FUNCION QUE DEVUELVA LOS MENORES E IGUALES QUE 3*/
